name: instant_aid
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  percent_indicator: ^4.2.3
  whisper_ggml: ^1.7.0  
  record: ^6.1.2
  flutter_sound: ^9.2.13    # for recording audio
  path_provider: ^2.0.15    # to save audio files
  permission_handler: ^11.0.1
  image_picker: ^1.2.1

  # Supabase
  supabase_flutter: ^2.0.0

  # TensorFlow Lite
  tflite_flutter: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ggml-tiny.bin
    - assets/model.tflite
    - assets/tokenizer.json
    - assets/vocab.txt
